// <auto-generated />
namespace NTHBaiTapLon513.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cap_nhat_5_bảng : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cap_nhat_5_bảng));
        
        string IMigrationMetadata.Id
        {
            get { return "202203221442538_cap_nhat_5_bảng"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
